services:
  - type: web
    name: birthday-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TIMEZONE
        value: Europe/Moscow
      - key: WEBHOOK_URL
        sync: false
      # PORT устанавливается автоматически Render 