services:
  - type: web
    name: birthday-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8012067557:AAGkdq_fUfomek-ee9CRsyjm6BHZ0dEl8NA
      - key: TIMEZONE
        value: Europe/Moscow
      - key: WEBHOOK_URL
        sync: false
      # PORT устанавливается автоматически Render 